name: 'postgres'

services:
  postgres:
  # postgres:16
    image: postgres@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: epayjsc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    # env_file:
    #   - .env
    restart: always
    networks:
      - network1

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin
  #  ports:
  #    - 15433:80
  #  env_file:
  #    - .env
  #  depends_on:
  #    - postgres
  #  networks:
  #    - network1
  #  volumes:
  #    - ./pgadmin/:/var/lib/pgadmin/
    
networks:
  network1:
    name: docker_network
    external: true

volumes:
  postgres_db:
    name: postgres_db
    driver: local